name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./daydream

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.139.2'

      - run: hugo --minify

      - uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PAT }}
          external_repository: zhongqingg/zhongqingg.github.io
          publish_branch: main
          publish_dir: ./daydream/public
